
name: Fork Automerge Caller

# Harmonization update
on:
  pull_request_review:
    types: [submitted]
  check_run:
    types: [completed]
  workflow_dispatch:

jobs:
  automerge:
    # Berechtigungen m√ºssen direkt im Job stehen
    permissions:
      contents: write
      pull-requests: write
    uses: lemueIO/.github/.github/workflows/central-automerge-logic.yml@main
    with:
      runs_on: ${{ (github.repository == 'lemueIO/villa-kunterbunt' || github.repository == 'derlemue/villa-kunterbunt') && 'self-hosted' || 'ubuntu-latest' }}
    secrets: inherit
