name: Sync Fork Caller

# Harmonization update
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

# Globale Berechtigungen f√ºr das Token des Callers
permissions:
  contents: write
  pull-requests: write

jobs:
  call-sync-fork:
    if: github.repository != 'derlemue/villa-kunterbunt'
    # ...und stellen sicher, dass der Job sie auch wirklich anwenden darf
    permissions:
      contents: write
      pull-requests: write
    uses: lemueIO/.github/.github/workflows/central-sync-logic.yml@main
    with:
      upstream_url: "https://github.com/derlemue/villa-kunterbunt.git"
      runs_on: 'self-hosted'
    secrets: inherit
