# Standard Sync Fork Caller (Harmonized)
name: Sync Fork Caller
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  call-sync-fork:
    if: github.repository != 'derlemue/villa-kunterbunt'
    permissions:
      contents: write
      pull-requests: write
    uses: lemueIO/.github/.github/workflows/central-sync-logic.yml@main
    with:
      upstream_url: "https://github.com/derlemue/villa-kunterbunt.git"
      runs_on: 'ubuntu-latest'
    secrets: inherit
